# Generated by Django 5.2.9 on 2026-02-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='desceription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumeupload',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
