# Generated by Django 5.2.9 on 2026-02-13 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_imageupload_desceription_resumeupload_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageupload',
            old_name='desceription',
            new_name='description',
        ),
    ]
